language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: oLieGqGxKHopqI7j50o5KODi9NkWYxCXr5VgM5zoHngFfVu310hscM5PzKcTb4poGPFRZ1qCGOxgs9d5K3sWE1is3OWHzEn2hC6J1AuVT7zE/CGc8Po1lmM0fSHv7/roT7C119oM5BYbAiNroDrmSQcBS+OYu2spn9o6CPyizjT2b6g1qEDB0//TdtHOkvnanoUvhwbkaQ/RCHkqctGoPkAJiKAYymX2yCK/5/7gZOEcGYaTaBA5o1dWFT1n8jfjiyhrqBLW162Q3qd5WAe1rdyCwJVxg/pARaGRuJbBJdz6hx/zpSrpk5LxpoDltH1Y0vN3NlVjIODjvlxYodI0dtCfPeLkgV3HDRrfjJVrfH72cOIPdPVJN5cqhbqqb8EU/wb2qvB5b+NUtwNUK2veA7T9qHmTAgx1gNNZJPxRYfdEaysCYwOtqdek02hdF5KWUsZtJZ0zYSNP02vnmygDF1l13OgZKkjGxm1vIv249O0C+JSWLqt3k5vy0iR/bVTdySPrAxUa6rC5ahz+2Yw/zb43PloisOy2WZ7nQc1PpSDiwP/+n2G6Wf0Q7rgTlTv6Wc0oIhuiBg10SzWe2rjokFYVwqokfKHFwWdJHk6sDmGZNh8zUI2Zmtg2VrwvNFWM811NXICBxjvbCPlDh6i3bx+GHY8w7w6RQgdQsHoOn90=
  app: limitless-bayou-12140
  on:
    repo: sowmyag12/node-shopping-list-integration-tests
